### PR TITLE
Add packages documentation

### PR DESCRIPTION
**Pull request by mudler**
This is just adding some placeholders, I'll add up docs but wanted to have all in place and see how it looks like
 before going ahead

Part of: https://github.com/rancher-sandbox/cOS-toolkit/issues/757

### CODE REVIEW

**Comment by davidcassany** [comment]
@mudler JFYI in #909 I am doing little cleanup on packages deps and I saw there is not need for a collection here as we are building a single package. I moved the `collection.yaml` to a `definition.yaml`.

**Comment by mudler** [comment]
yep, noticed the same here indeed, no worries, I can re-adapt after your PR is merged :+1:

**Comment by mudler** [comment]
ok, reworked out so it just applies the README.md file and leaves the specs untouched so it's easier to rebase later

**Comment by mudler** [comment]
Just moved some docs and added placeholders. merging because it is tight with the other PR, and docs were now missing from the website :sweat_smile:

**Pull request merged**
