### PR TITLE
amazon: Copy vanilla image to all regions

### PR DESCRIPTION
**Pull request by Itxaka**
Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
Not really tested...

**Review by mudler — APPROVED** [review]
Looks good, let's see how it behaves on master :+1:

**Comment by Itxaka** [comment]
mmmh...build seems to not have started at all ?

**Review by davidcassany — APPROVED** [review]
Looks good.

My only concern, not really exclusively tied to this PR is that we are starting to upload quite some stuff in AWS. Would be nice to have some sort of garbage collector policy, so just keep up to certain amount of artifacts of a kind, or keep binaries only for X time, etc.

**Comment by Itxaka** [comment]
@davidcassany indeed, once we have LifecyclePolicy permissions we can start adding policies to keep only X images or images newere than X days ago

**Comment by mudler** [comment]
The only way to test this is on master :)

**Pull request merged**
