### PR TITLE
[CI] Publish AMI

### PR DESCRIPTION
**Pull request by Itxaka**
This patch adds a new job on github for the master branch that requires
the publish step to have passed and we use packer to build an AMI based
of the latest master image pushed and store it on aws

Closes: #334 

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by mudler** [comment]
out of curiosity, did you tried also to run the packer template against the published image?  maybe we should update somewhere in the docs what's the public url

**Review by mudler — APPROVED** [review]

**Comment by Itxaka** [comment]
> out of curiosity, did you tried also to run the packer template against the published image? maybe we should update somewhere in the docs what's the public url

@mudler do you mean run with base for this the final image? like generate an image from this and then use that as a base for generating another one?

I havent done that...like...why would you do that? If you are generating an image you start from a "clean" one no? And nothing better than the recovery image for that :D

**Comment by mudler** [comment]
> > out of curiosity, did you tried also to run the packer template against the published image? maybe we should update somewhere in the docs what's the public url
> 
> @mudler do you mean run with base for this the final image? like generate an image from this and then use that as a base for generating another one?
> 
> I havent done that...like...why would you do that? If you are generating an image you start from a "clean" one no? And nothing better than the recovery image for that :D

I mean, the published AMI image has the scope of being a base to put something on, we have to keep in mind that https://github.com/ibuildthecloud/os2 is one of the use cases. 

In that case I expect the user to be able to run the packer template on top of our published one - with the only input be the container image reference

**Comment by Itxaka** [comment]
if by published AMI you mean the recovery one, then yes. Using the packer templates and pointing to it should result in a working cos image without touching anything else. If you want to customize then setting the install command to your docker-image should results in a customized AMI with your os on it, like pointing it to install `cos-deploy --no-verify --docker-image docker.io/ibuildthecloud/os2-0.1.0` should end up with a custom os2 AMI published...in theory.


Not tested of course, is there any published artifacts from os2 that I could test with?

**Comment by mudler** [comment]
> if by published AMI you mean the recovery one, then yes. Using the packer templates and pointing to it should result in a working cos image without touching anything else. If you want to customize then setting the install command to your docker-image should results in a customized AMI with your os on it, like pointing it to install `cos-deploy --no-verify --docker-image docker.io/ibuildthecloud/os2-0.1.0` should end up with a custom os2 AMI published...in theory.
> 
> Not tested of course, is there any published artifacts from os2 that I could test with?

That already is enough :+1: but yup btw we have an image `quay.io/costoolkit/test-images:os2`

**Review by davidcassany — APPROVED** [review]

**Pull request merged**
