### PR TITLE
ci: Cancel pending jobs on PR close/merge

### PR DESCRIPTION
**Pull request by Itxaka**
No point in having jobs running once the PR is merged or closed

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
will have to be updated once https://github.com/rancher-sandbox/cOS-toolkit/pull/681 is merged

**Comment by mudler** [comment]
question: does it cancel just jobs associated with the PR, or all jobs matching the workflow ?

**Comment by Itxaka** [comment]
> question: does it cancel just jobs associated with the PR, or all jobs matching the workflow ?

jobs matching the **branch**

Usually is matching the branch and sha, so it can cancel old jobs for a branch, but in our case we want to cancel all jobs from branch X ignoring the sha, as it wont change on close event.

**Review by mudler — APPROVED** [review]

**Comment by mudler** [comment]
sounds great! let's go for it.. no sense to wait for CI here

**Comment by Itxaka** [comment]
Need to update to add the new docker workflow

**Comment by Itxaka** [comment]
I guess we may see if it works rigth now or crashes and burns and cancels the whole org jobs LMAO

**Pull request merged**
