### PR TITLE
ci: add cleanup images plugin

### PR DESCRIPTION
**Pull request by mudler**
Attempt to free up space during build (related to #917 )

### CODE REVIEW

**Comment by mudler** [comment]
Rebased on top of #935

**Review by Itxaka — COMMENTED** [review]
Yikes. Can't we simply docker system prune -a and call it a day? That should clean up everything not being used no?

Also, what do we expect to clean up from this? Aren't ci nodes spin up from scratch on each job?

**Comment by mudler** [comment]
> Yikes. Can't we simply docker system prune -a and call it a day? That should clean up everything not being used no?
> 
Yes and no, I mean we definitely can delete all images after we finish building one package, the plugin is just a safeguard to avoid going to look at this again

> Also, what do we expect to clean up from this? Aren't ci nodes spin up from scratch on each job?
Nope, we run 1 job building all images, rationale is explained #917 . we can split build into multiple, but that has other problems as well (starvation)

**Review by Itxaka — APPROVED** [review]

**Comment by mudler** [comment]
I think with #278 we can disable the plugin and the cleanup, and just run it after the whole build.. but keeping it for now until we have self-hosted runners

**Pull request merged**
