### PR TITLE
ci: Reintroduce the check on raw test vm boot

### PR DESCRIPTION
**Pull request by Itxaka**
Lets wait after launching the vm for testing until we see the welcome
message

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Review by mudler — APPROVED** [review]
Even if hardcoded sleeps are unpleasant, I'd merge this as-is. Better have stable tests than flaky ones

**Comment by davidcassany** [comment]
I'd wait for my PR (https://github.com/rancher-sandbox/cOS-toolkit/pull/557) to finalize before merging this if you don't mind. There I did a couple of changes to speed up boot. Default SATA ports number is 30 and this has a huge impact on boot and causes at least a failure on initial `OEM` mount (even this should not hurt it might have impact on boot time).

**Comment by Itxaka** [comment]
oh I see, so if you dont specify it just  creates 30 ports?? Wow.

**Comment by mudler** [comment]
> oh I see, so if you dont specify it just creates 30 ports?? Wow.

you never know right.. :rofl:

**Comment by Itxaka** [comment]
closed in favour of #591

**Pull request closed without merging**
