### PR TITLE
Delete cloud instances

### PR DESCRIPTION
**Pull request by Itxaka**

### CODE REVIEW

**Review by mudler — APPROVED** [review]

**Comment by Itxaka** [comment]
This has been tested with 2 of my instances and it removed them correctly. Also it left the one in the exclude list alone.

**Comment by mudler** [comment]
No sense to wait for tests here :+1: let's just merge it @Itxaka ?

**Comment by Itxaka** [comment]
one sec @mudler !!!

**Comment by Itxaka** [comment]
there we go @mudler as small safeguard against running the script locally!

**Pull request merged**
