### PR TITLE
Live mode

### PR DESCRIPTION
**Pull request by mudler**
Docs: https://github.com/rancher-sandbox/cos-toolkit-docs/pull/29

### CODE REVIEW

**Review by kkaempf — COMMENTED** [review]
Where do you test existance of `/run/cos/live_mode` and its content ?

**Comment by mudler** [comment]
> Where do you test existance of `/run/cos/live_mode` and its content ?

we don't, I've tested this manually as we don't have tests running on livecd

**Comment by kkaempf** [comment]
Hmm, livecd testing probably cannot be automated with github workers 🤔 
Then we should have a test document for manual testing where the sentinel file is checked.

**Comment by mudler** [comment]
> Hmm, livecd testing probably cannot be automated with github workers thinking
> Then we should have a test document for manual testing where the sentinel file is checked.

We don't have a test document, or I am missing something?

**Comment by Itxaka** [comment]
> Hmm, livecd testing probably cannot be automated with github workers


Why not? We are already testing recovery images which are also "live". The sky is the limit!

**Comment by mudler** [comment]
I've created https://github.com/rancher-sandbox/cOS-toolkit/issues/581 with what I had in mind now, but pretty sure the list isn't exhaustive at all :slightly_smiling_face:

**Comment by mudler** [comment]
> > Hmm, livecd testing probably cannot be automated with github workers
> 
> Why not? We are already testing recovery images which are also "live". The sky is the limit!

the limit is also how many concurrent job that uses virtualization we can have...

**Review by Itxaka — APPROVED** [review]

**Comment by Itxaka** [comment]
> the limit is also how many concurrent job that uses virtualization we can have...
@kkaempf is gonna get us a few of those AMD Epyc servers, so that is fixed already :P

**Comment by kkaempf** [comment]
> @kkaempf is gonna get us a few of those AMD Epyc servers, so that is fixed already :P

You provide the cooling, I provide the servers. Deal ?

**Comment by Itxaka** [comment]
> You provide the cooling, I provide the servers. Deal ?

Send them my way, I'll store them at home. Did you said that they had nice GPUs? BRB, looking for the GPU requirements to run cyperpunk 2077...

**Review by Itxaka — APPROVED** [review]

**Pull request merged**
