### PR TITLE
Bump toolchain/elemental-cli to 0.20220214

### PR DESCRIPTION
**Pull request by cOS-cibot**
Signed-off-by: cOS-cibot [bot] <cOScibot@gmail.com>

Be careful not to remove the branch you're standing on

### CODE REVIEW

**Review by mudler — APPROVED** [review]

**Comment by Itxaka** [comment]
will manually bump it with todays changes, no need for this

**Comment by mudler** [comment]
ok :+1: it was blocking https://github.com/rancher-sandbox/os2/issues/16 as it needs the changes published to go ahead, that's why I was retriggering it :smile:

**Comment by Itxaka** [comment]
wops, sorry about that @mudler , didnt know! The new elemental should come in about a couple of minutes on https://github.com/rancher-sandbox/cOS-toolkit/pull/1122

**Comment by mudler** [comment]
> wops, sorry about that @mudler , didnt know! The new elemental should come in about a couple of minutes on #1122

no worries! if the other one gets in before, no need for this one!

**Comment by Itxaka** [comment]
bah, I reopened to see if it got the old CI jobs and could be merged fast, looks like not :/ @mudler should we force push so you are not blocked?

**Comment by mudler** [comment]
> bah, I reopened to see if it got the old CI jobs and could be merged fast, looks like not :/ @mudler should we force push so you are not blocked?

Better go with https://github.com/rancher-sandbox/cOS-toolkit/pull/1122 , so I can also wire it up with the new upgrade changes and check regressions eventually as well :+1: 

At the moment I'm looking at https://github.com/rancher-sandbox/os2/issues/7, so there is no rush :relaxed:

**Pull request closed without merging**
