### PR TITLE
Fix package names on rpi/odroid docker builds

### PR DESCRIPTION
**Pull request by Itxaka**
Theya re different on tumbleweed

Fixes: https://github.com/rancher-sandbox/cOS-toolkit/issues/1353

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
umm, I talked too soon, not fixed yet.

`Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory`

**Review by mjura — APPROVED** [review]
LGTM

**Comment by Itxaka** [comment]
The issue above seems to be my own configuration ofthe cross buildx stuff :)

**Comment by Itxaka** [comment]
requires #1358 to be merged and packages published for green

**Pull request merged**
