### PR TITLE
gce: Add script to create ready-to-upload disk to gce

### PR DESCRIPTION
**Pull request by Itxaka**
Same as the other images, this adds a script to prepare the raw disk in
a format that can be uploaded to gce and then imported directly as image

GCE as has some caveats:
 - Image needs to be rounded up to the next Gb
 - Image needs to be tar.gzipped with oldgnu format
 - Image inside the tar needs to be called disk.raw

Those are the main changes from the normal raw disk

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
@davidcassany My thougths exactly. When it was 1 it was ok. 2 was starting to stretch. 3 is now way too much, and both gc and azure use raw_img as base so they can use the same file.

Mainly sent this because I was testing a bit and didnt want to leave the script lying around and forget about it. I dont even know if it works (it uploads and you cna import it as image, but Im not sure it works)

**Comment by Itxaka** [comment]
reworked to build all at the same time, rename them properly and add extra info to their naming, both files and artifacts.

GCE image tested to work as expected :o

**Comment by Itxaka** [comment]
Need to leave, writing down here the steps to upload and create an image from the raw disk:

```
$ gsutil cp cos-vanilla-0.5.8+2.tar.gz gs://cos_images/
$ gcloud compute images create cos-vanilla-0-5-8plus2 --project=suse-css-platform --source-uri=https://storage.googleapis.com/cos_images/cos-vanilla-0.5.8\+2.tar.gz --storage-location=eu --guest-os-features=UEFI_COMPATIBLE --family=cos-vanilla --labels="flavor=vanilla,name=cos,version=0-5-8_2"

```

where:
 - --guest-os-features=UEFI_COMPATIBLE is required so machines with this image boot with UEFI, otherwise it tries legacy boot and it fails
 - --family=cos-vanilla : `The family of the image. When creating an instance or disk, specifying
        a family will cause the latest non-deprecated image in the family to be
        used.` so this is used to filter if you were to choose your boot image as cos-vanilla it would pick the latest version.
 - --labels: for easy filtering.

**Review by mudler — APPROVED** [review]

**Comment by mudler** [comment]
Nice! :tada:

**Review by davidcassany — APPROVED** [review]
Cool, looks good

**Pull request merged**
