### PR TITLE
Add disk raw test

### LINKED ISSUE #486: Add small test for raw image
**Is your feature request related to a problem? Please describe.**
When modifying source, sometimes its possible that we break the raw image, but we dont have any tests for it

**Describe the solution you'd like**
A simple test added to the tests that uses the raw image as base to check that at least it boots as expected

**Describe alternatives you've considered**
n/a

**Additional context**

### PR DESCRIPTION
**Pull request by Itxaka**
closes #486

### CODE REVIEW

**Comment by Itxaka** [comment]
Lookign for some feedback as this boots the image but it doesnt seem to work as expected (also tested locally with the raw_disk)

Did we break the raw_disk already? Am I doing something weird?

**Comment by Itxaka** [comment]
umm, I migth have broken the raw_disk with the grub artifacts?


```
   Falling back to `cOS recovery'

 hd0,gpt4error: ../../grub-core/loader/i386/efi/linux.c:277:can't allocate kernel.
error: ../../grub-core/loader/i386/efi/linux.c:98:you need to load the kernel first.

Press any key to continue...
```

**Comment by Itxaka** [comment]
ahh seems like I forgot to increase the memory if the vm so grub fails to boot (not able to map the kernel maybe? mount the loop device?)

**Comment by Itxaka** [comment]
can this be reviewed and merged? @mudler @dragonchaser only the vbox-squashfs failed due to virtualbox crapping out, the rest went green without issues :)

**Review by mudler — APPROVED** [review]
Looks good! having a simple smoke test for it it's nice, and shouldn't even take long in the test matrix

**Pull request merged**
