### PR TITLE
Bump toolchain/luet to 0.16.6

### PR DESCRIPTION
**Pull request by cOS-cibot**
documentation

### CODE REVIEW

**Review by mudler — APPROVED** [review]
Waiting for CI tests

**Comment by mudler** [comment]
I've opened an issue for #277  . The timeouts issues looks like a recurring problem which seems genuine to me.

**Comment by mudler** [comment]
I'm having a look closer, it looks like it fails 100% of times during upgrade tests

**Comment by davidcassany** [comment]
Yes something odd is happening. See that https://github.com/rancher-sandbox/cOS-toolkit/pull/272 also fails on upgrade tests but with a different error... something related to xattrs not being copied by rsync... @_@ I was looking at upgrade tests now too

**Comment by mudler** [comment]
> Yes something odd is happening. See that #272 also fails on upgrade tests but with a different error... something related to xattrs not being copied by rsync... @_@ I was looking at upgrade tests now too, and of course they pass locally cry

I've opened a separate PR for that :+1:  #283

**Comment by mudler** [comment]
Ok, something seems definetly not ok, this is what I get trying manually:

```
os:~ # luet --version
luet version 0.16.6-ga7b4ae67c9b86b22bd706df7cde43fdfd5121772 2021-06-16 09:14:14 UTC
cos:~ # cos-upgrade
Upgrading system..
-> Upgrade target: active.img
3240+0 records in
3240+0 records out
3397386240 bytes (3.4 GB, 3.2 GiB) copied, 5.25743 s, 646 MB/s
mke2fs 1.43.8 (1-Jan-2018)
Discarding device blocks: done                            
Creating filesystem with 829440 4k blocks and 207584 inodes
Filesystem UUID: 32acc853-434a-44e8-a4bb-fbc55f3e7d00
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200

Allocating group tables: done                            
Writing inode tables: done                            
Writing superblocks and filesystem accounting information: done 

 Enabled plugins:
         image-mtree-check
 Downloading quay.io/costoolkit/releases-opensuse:repository.yaml
\  Pulled: sha256:46605c2f5987d28433b921b9b7c3bc3dad07e66b6d66a4465e905328937008f7
 Size: 640B
 Downloading quay.io/costoolkit/releases-opensuse:tree.tar.zst
-  Pulled: sha256:ec728a638d26d1a3c12d5b573d755005a037fb9499a161009e7114b28cd01b24
 Size: 2.547KiB
 Downloading quay.io/costoolkit/releases-opensuse:repository.meta.yaml.tar.zst
-  Pulled: sha256:c510d8ab087499df16cf90d188b1e867d0d8f9824712f8becbb2f9a0a853ed01
 Size: 198.6KiB
  Repository cOS revision: 16 - 2021-06-12 2030 +0000 UTC
/  Repository: cos Priority: 1 Type: docker
 Packages that are going to be installed in the system: 
  cos-system-0.5.3+1 (cos)
 Downloading image quay.io/costoolkit/releases-opensuse:cos-system-0.5.3-1
\  Pulled: sha256:1787478f4c27e46d8865e511039506d45de6cfa1ca0e5d575e25160d7a8facb4
 Size: 638.8MiB
  Package  system/cos-0.5.3+1 downloaded
  Package  system/cos-0.5.3+1 installed
 Cleaned:  0 packages.
tune2fs 1.43.8 (1-Jan-2018)
tune2fs 1.43.8 (1-Jan-2018)
Flush changes to disk
Upgrade done, now you might want to reboot
cos:~ # reboo^C
cos:~ # cat /etc/os-release 
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/mudler/cOS/issues"
DOCUMENTATION_URL="https://github.com/mudler/cOS"
HOME_URL="https://github.com/mudler/cOS"
ID="cOS"
NAME="cOS"
PRETTY_NAME="cOS v0.5.3+2"
cos:~ # reboot
Connection to 127.0.0.1 closed by remote host.
Connection to 127.0.0.1 closed.

~/_git/cOS/tests cos-ci-forks-bump_luet_toolchain* 2m 50s
❯ vagrant ssh
Password: 
```

**Comment by mudler** [comment]
To note, the release after booting it's fine. It's just that I cannot anymore login via ssh

**Comment by mudler** [comment]
VirtualBox_tests_default_1623836200067_3343_16_06_2021_11_44_56


Even more puzzling, the user is there.. and also the ssh keys

VirtualBox_tests_default_1623836200067_3343_16_06_2021_11_46_26

**Comment by davidcassany** [comment]
Is the IP the same one after reboot? probably this is a known_hosts issue, I am seeing it in libvirt.

**Comment by mudler** [comment]
> Is the IP the same one after reboot? probably this is a known_hosts issue, I am seeing it in libvirt. If so probably persisting some of the volatile wicked config files might do the trick.

yup, I always get `10.0.2.15` in the VM. The weird thing is that if I set a password to the vagrant user, and later I `ssh-copy-id` my identity, I can login just fine ..

**Comment by mudler** [comment]
Definetly it's something happening after a reboot. If I switch back to the fallback partition which is the same one where I was booting at the beginning, I can't login from there as well

**Comment by mudler** [comment]
Another weird thing I'm noticing. Even if `/etc/machine-id` seems to persist correctly, across reboot I get prompted to re-trust the host anytime. Note I connect over it via `127.0.0.1:2222` all the times

**Comment by davidcassany** [comment]
> Another weird thing I'm noticing. Even if `/etc/machine-id` seems to persist correctly, across reboot I get prompted to re-trust the host anytime. Note I connect over it via `127.0.0.1:2222` all the times

SSH finger prints are recreated on each boot, see `/etc/ssh` probably we should persist that too.

**Comment by mudler** [comment]
> > Another weird thing I'm noticing. Even if `/etc/machine-id` seems to persist correctly, across reboot I get prompted to re-trust the host anytime. Note I connect over it via `127.0.0.1:2222` all the times
> 
> SSH finger prints are recreated on each boot, see `/etc/ssh` probably we should persist that too.

oh right! I just assumed we persisted all of those. Going to try that :+1:

**Comment by davidcassany** [comment]
What I can't understand it why is this poping up right now, its been like that since the very beginning :man_shrugging:

**Comment by mudler** [comment]
> What I can't understand it why is this popping up right now, its been like that since the very beginning man_shrugging

Yep indeed..

**Comment by davidcassany** [comment]
I just saw another failure that might cause this sort of issues, one of my local tests execution failed to login after reboot. I logged into the machine directly on tty0 from VirtualBox and I saw dbus service failed to start because of hitting restart limit, complaining of too many repeated restarts in short time, this causes a wicked service failure too, so it did not get any IP...

**Comment by mudler** [comment]
I've tried to move back to the old mechanism we used to unpack images: https://github.com/mudler/luet/commit/8780e4f16fb9c8942ebce1e06081dd03dac3f565 - but testing locally yields the same results

**Comment by mudler** [comment]
Created #286 for the persisting the ssh generated keys on first-boot

**Comment by mudler** [comment]
I'll try to see if the issue is still there with `0.16.5`. if that works I'll do a switch with an env var to enable unpriv installs from packages in containers

**Comment by mudler** [comment]
Alright, looks indeed an issue with the usage of unprivileged installs. A switch might do it for the time being ( see #287 )

**Pull request closed without merging**
